In [1]:
import tensorflow as tf

构建1个1行2列，及2行1列的常量。

In [2]:
matrix1 = tf.constant([[3., 3.]])

In [3]:
matrix2 = tf.constant([[2.],[2.]])

In [4]:
product = tf.matmul(matrix1, matrix2)

In [24]:
sess = tf.Session()

result = sess.run(product)

print(result)

[[ 12.]]


In [25]:
sess.close()

以下是numpy的ndarray的基本用法

In [7]:
import numpy as np

In [8]:
x = np.array([[3, 3]])

In [9]:
x

array([[3, 3]])

In [10]:
x.shape

(1, 2)

In [11]:
x1 = np.array([3, 3])

In [12]:
x1.shape

(2,)

In [13]:
x1

array([3, 3])

In [14]:
x2 = np.array([[3], [3]])

In [15]:
x2.shape

(2, 1)

In [16]:
x = np.arange(10)

In [17]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x.shape

(10,)

In [21]:
x4 = x.T

In [22]:
x4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x4.shape

(10,)

回到tensorflow

In [26]:
with tf.Session() as sess:
    result = sess.run(product)
    print(result)

[[ 12.]]


以下是交互式tensorflow会话, 可用eval和xxx.run代替session.run

In [27]:
import tensorflow as tf

In [28]:
sess = tf.InteractiveSession()

In [29]:
x = tf.Variable([1.0, 2.0])

In [31]:
a = tf.constant([3.0, 3.0])

In [32]:
x.initializer.run()

In [37]:
add1 = tf.add(x, a)

In [39]:
print(add1.eval())

[ 4.  5.]


变量

In [42]:
# 创建一个变量, 初始化为标量 0.
state = tf.Variable(0, name="counter")

# 创建一个 op, 其作用是使 state 增加 1

one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

# 启动图后, 变量必须先经过`初始化` (init) op 初始化,
# 首先必须增加一个`初始化` op 到图中.
init_op = tf.global_variables_initializer()

# 启动图, 运行 op
with tf.Session() as sess:
  # 运行 'init' op，
  sess.run(init_op) #（我理解这里只是执行变量的初始化，其他如add,assign等并不会被执行）
  # 打印 'state' 的初始值
  print(sess.run(state)) #RUN一个变量，就是返回这个变量的值
  # 运行 op, 更新 'state', 并打印 'state'
  for _ in range(3):
    sess.run(update) #此处才真正执行update
    print(sess.run(state)) #执行update之后再次输出state

0
1
2
3


Fetch操作

In [65]:
input1 = tf.constant(3.0)
input2 = tf.constant(2.0)
input3 = tf.constant(5.0) 
var1 = tf.Variable(1, name="var1")
intermed = tf.add(input2, input3)
mul = tf.multiply(input1, intermed)

In [46]:
with tf.Session() as sess: #没有initil操作，意味着上面的常量并不需要被初始化
  result = sess.run([mul, intermed]) #RUN输入的参数一是代表执行，二是取回。
  print(result)

[21.0, 7.0]


In [50]:
with tf.Session() as sess: #没有initil操作，意味着上面的常量并不需要被初始化
  result = sess.run(intermed) #RUN输入的参数一是代表执行，二是取回。
  print(result) # 只执行了intermed，没执行mul。
  print(mul) #所以这里还是只输出了一个张量
  print(sess.run(mul)) #这里才输出具体的值

7.0
Tensor("Mul_1:0", shape=(), dtype=float32)
21.0


In [67]:
with tf.Session() as sess:
    print(sess.run(input1)) #常量不用initializer()来初始化可以直接输出
    #print(sess.run(var1)) #变量没有initializer()初始化，直接输出会报错
    sess.run(tf.global_variables_initializer()) #对变量初始化
    print(sess.run(input1)) 
    print(sess.run(var1)) #可以正常输出1
    print(sess.run([var1])) #输出[1]

3.0
3.0
1
[1]


Feed操作

In [68]:
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)
output = tf.multiply(input1, input2)

with tf.Session() as sess:
  print(sess.run([output], feed_dict={input1:[7.], input2:[2.]}))
  print(sess.run(output, feed_dict={input1:7., input2:2.}))

[array([ 14.], dtype=float32)]
14.0
